YACReader/main.cpp
config.pri

This PR fixes YACReader build using Qt 5.6 and 5.7.
Impact on other versions is minimal, so it is a low-risk merge. Fast review would be appreciated as I'd like to use this for a 9.5.1 bugfix release (Linux, source code release only).

9.5.0 fixes

---

YACReaderLibrary/main.cpp
YACReaderLibrary/server/server.pri
YACReaderLibrary/server/startup.cpp
YACReaderLibraryServer/main.cpp

This pr improves the ability to debug YACReaderLibrary and Server. It adds the following features:
- loglevel commandline option to set the desired log level
- replace QtWebApp's logger with a QsLog based message handler. This prevents QtWebApp from eating our debug messages and allows control over the server log level
- add opengl renderer selection on Windows to the commandline (this one isn't really tested yet)
Stuff still missing:
- silent commandline option to prevent Library/Server from spamming the commandline

Server logging 2.0

---

YACReaderLibrary/server/controllers/v2/pagecontroller_v2.cpp

In my case, I am compiling YACReader against `musl` libc, under Alpine Linux.
`musl` is known to have a stack size much smaller than `glibc`, thus explaining why the issue is not seen on most platforms.

Fixed potential stack overflow.

---

YACReader/render.cpp

The indentation suggests that the line that update `previousIndex` was meant to be inside the `if`, but the lack of braces means it isn't. I don't think it was an indentation error.
This bug was discovered while fixing the warnings of gcc compilation. See #40.

bug: 'else' without braces but several lines indented

---

common/opengl_checker.cpp

OpenVG can't be detected because of an obvious bug.
This bug was encountered while fixing the compilation warnings of gcc. See #40.

bugfix: 'switch case' for OpenVG had no 'break'

---

CHANGELOG.md
README.txt

This pr fixes utf8 encoding problems in README.txt and CHANGELOG.md. We likely still have a lot of these in the old spanish source comments, but I won't hunt them ;)
Special thanks to @tim77 for bringing this annoying little problem back to my attention.

utf8 encoding fixes

---

YACReader/render.cpp
YACReader/viewer.cpp
YACReader/yacreader_local_client.cpp
YACReaderLibrary/comic_vine/comic_vine_dialog.cpp
YACReaderLibrary/comic_vine/model/response_parser.cpp
YACReaderLibrary/db/comic_model.cpp
YACReaderLibrary/db/data_base_management.cpp
YACReaderLibrary/db/folder_model.cpp
YACReaderLibrary/db/reading_list_model.cpp
YACReaderLibrary/db_helper.cpp
YACReaderLibrary/import_widget.cpp
YACReaderLibrary/library_window.cpp
YACReaderLibrary/properties_dialog.cpp
YACReaderLibrary/server/controllers/v2/librariescontroller_v2.cpp
YACReaderLibrary/server/lib/httpserver/staticfilecontroller.cpp
YACReaderLibrary/server/requestmapper.cpp
YACReaderLibrary/server/startup.cpp
YACReaderLibrary/server/yacreader_http_session.cpp
YACReaderLibrary/yacreader_local_server.cpp
YACReaderLibrary/yacreader_navigation_controller.cpp
common/comic.cpp
common/comic_db.cpp
common/gl/yacreader_flow_gl.cpp
common/pictureflow.cpp
common/scroll_management.cpp
custom_widgets/yacreader_busy_widget.cpp
custom_widgets/yacreader_busy_widget.h

This branch fixes the compilation warnings of gcc. This replaces #40 (the context is described there).
As requested, I've moved some bugs discovered here into separated branches : #41 and #42.
I've also changed my commit policy to make micro-commits that should be easier to rebase.

Fix gcc8 warnings

---

YACReaderLibrary/qml/FlowView.qml

Adds vertical navigation (up down) to FlowView. This corresponds visually to the File Name list display -- especially when the flow pane is hidden, pressing up-down is the intuitive way to navigate up-down in the list.

Add Up Down navigation to FlowView

---

YACReaderLibrary/server/startup.cpp

[`Startup::stop()`](https://github.com/YACReader/yacreader/blob/87a66458751b5486eb40b7a54ab3214704a3666a/YACReaderLibrary/server/startup.cpp#L132) called from [`LibraryWindow::closeEvent()`](https://github.com/YACReader/yacreader/blob/87a66458751b5486eb40b7a54ab3214704a3666a/YACReaderLibrary/library_window.cpp#L2415) crashes if `listener` is not initialized.

Library: fix a crash at exit when server is disabled

---

YACReader/goto_flow.cpp
YACReader/goto_flow.h

GoToFlow shared its YACReaderFlow flow object with SlideInitializer
objects it created. GoToFlow modified the flow object in the main thread
and SlideInitializer modified the flow object in its own thread without
any thread synchronization. The only reason this usually worked was the
timing: SlideInitializer finished its work before the next time GoToFlow
heavily accessed the flow object. This was a data race and thus
undefined behavior.
Additionally, this commit eliminates a memory leak:
a new SlideInitializer object was constructed each time a comic was
opened in YACReader. These objects were never destroyed.
SlideInitializer called PictureFlow::triggerRender() from its own
thread. This function restarted triggerTimer, which QTimer's API forbids
doing from another thread. This commit …

Reader: eliminate SlideInitializer class

---

YACReader/render.cpp
YACReaderLibrary/server/controllers/v1/comiccontroller.cpp
YACReaderLibrary/server/controllers/v2/comiccontroller_v2.cpp
common/comic.cpp

Thread ping pong fix, second attempt. This one shouldn't cause gigantic memleaks like the first, but it does keep the comic objects in a dedicated thread during it's lifetime. The lifetime of the thread is always tied directly to the comic object. This roughly works like this:
1) Comic object is deleted and sends out "destroyed" signal. The signal is sent to the thread's "quit" slot
2) The thread finishes execution and sends out the "finished" signal. This is sent to the thread's "deleteLater" slot, which schedules the thread for deletion

Thread ping pong

---

YACReader/render.cpp
YACReaderLibrary/server/controllers/v1/comiccontroller.cpp
YACReaderLibrary/server/controllers/v2/comiccontroller_v2.cpp
common/comic.cpp

Reverts YACReader/yacreader#5
I am reverting this once more time, maybe I messed up during the rebase, but there is a memory leak in YACReader. To replicate it move to the next or previous comic before the current comic is fully processed (ctrl+left|right), this is happen at least when opening a comic from YACReaderLibrary, I can't reproduce it when using previous builds.

Revert "Thread ping pong"

---

README.md

When clicking on the hyperlink at https://github.com/YACReader/yacreader, it leads to a 404.

Fix the hyperlink to project releases in README

---

YACReaderLibraryServer/YACReaderLibraryServer.pro

This PR fixes the problem that our headless server used to default to a standalone build, which gives conflicts when installing both the headless server and YACReaderLibrary.
It also removes the directive removing all debug output (QT_NO_DEBUG_OUTPUT) as we no longer can remember why we added it in the first place and our new loglevel commandline option supercedes it anyway.

Fix headless server build defaults

---

azure-pipelines-windows-template.yml
azure-pipelines.yml

This PR fixes a few minor issues with our CI system:
- translate stray spanish parameter name "arquitecture" to english "architecture"
- increase Qt version for Windows builds to 5.12.6 (latest LTS version)
- fix Qt install paths for Windows builds - aqtinstall changed its defaults

Azure fixes for Windows

---

YACReaderLibrary/server_config_dialog.cpp

`AF_INET` is in `<sys/socket.h>` [according to](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_socket.h.html) POSIX.

Unbreak build on FreeBSD

---

YACReaderLibraryServer/console_ui_library_creator.cpp

When passing a nonexistent path to the console library creator or updator, the create and update functions exit without cleaning up all ressources. This patch fixes that behavior.

Fix possible memleaks in console library creator

---

CHANGELOG.md
YACReaderLibrary/comic_vine/comic_vine_dialog.cpp
YACReaderLibrary/db/comic_model.cpp
YACReaderLibrary/db/comic_model.h
YACReaderLibrary/db/data_base_management.cpp
YACReaderLibrary/db/folder_model.cpp
YACReaderLibrary/db/reading_list_model.cpp
YACReaderLibrary/db_helper.cpp
YACReaderLibrary/library_creator.cpp
YACReaderLibrary/library_creator.h
YACReaderLibrary/properties_dialog.cpp

Qt's database and query model requires that both the queries and the database
objects are out of scope before a database connection can safely be removed.
Solution: Properly encapsulate databases and queries in "{ }" and use a string
to cache the connection name for out-of-scope removal.

Fix object leaks in database code

---

CHANGELOG.md
YACReaderLibrary/server/startup.cpp
YACReaderLibrary/server/startup.h
YACReaderLibraryServer/main.cpp

Manual editing of a config file for setting a port is not ideal.
Solution: add a set-port command to save a port and also a
--port option to allow setting a temporary port during startup

Headless server: Add support for setting a port from commandline

---

YACReader/main_window_viewer.cpp
YACReader/viewer.cpp

See commit messages for details.
There is one more place where a temporary `QTimer` can be refactored into `QTimer::singleShot`: [`LibraryWindow::toNormal()`](https://github.com/YACReader/yacreader/blob/36c1cdd2dac57225aa4b9743120c2c71f7f6fab5/YACReaderLibrary/library_window.cpp#L2057). I am not touching that code for two reasons:
1. I can not test it because I don't have access to Mac.
2. I doubt that it currently works as intended because [`YACReaderMacOSXToolbar::show()`](https://github.com/YACReader/yacreader/blob/36c1cdd2dac57225aa4b9743120c2c71f7f6fab5/custom_widgets/yacreader_macosx_toolbar.h#L59) is a simple function. As far as I know, only slots can be connected to with the old signal and slot syntax.

Reader: fix restoring Info visibility

---

YACReaderLibrary/YACReaderLibrary.pro
YACReaderLibrary/comic_flow.cpp
YACReaderLibrary/comic_flow.h
common/release_acquire_atomic.h
common/worker_thread.h

This is the first pull request in a series of two. It introduces the common worker class and uses it instead of one of the 4 image loader classes. See commit messages for details.
Note: I don't like some of the formatting changes clang-format does. There aren't many templates, lambdas or default member initializers in YACReader code yet. Consider the results and see if you like them. If not, you could change some of the formatting rules. I'd be happy to reformat changes in this pull request afterwards :). These are clang-format changes to the initial version of this pull request: [clang-format-changes.patch.zip](https://github.com/YACReader/yacreader/files/3855411/clang-format-changes.patch.zip).

Unify image loader classes

---

common/comic.cpp
common/comic.h

Hi,
There is a qt plugin for AVIF image format here : https://github.com/novomesk/qt-avif-image-plugin/
We just need to drop **qavif.dll** there : imageformats/qavif.dll
This plugin is build with Microsoft Visual Studio 2019 and Qt **5.14.2** so the qt version must be updated on the azure pipeline.
I updated it from **5.12.6** to **5.15.1** and now it works well with avif images !
May be, you can add this plugin as a dependencies to be bundled with the installer ?
Thanks !
Regards,
Steve

Support for third party qt image plugins

---

CHANGELOG.md
YACReader/viewer.cpp
YACReader/viewer.h

Shortcuts for moving inside a page didn't work. Now they do.

Fixes move action shortcuts not working

---

YACReaderLibrary/qml/FlowView.qml

InfoComicsView constructor is the only function that connects to
FlowView's currentCoverChanged signal. Neither of the slots connected to
this signal handles the argument value index==-1. So when FlowView emits
this signal with index==-1, YACReaderLibrary crashes. Returning early
from either ComicsView::updateInfoForIndex() or
InfoComicsView::setCurrentIndex() when index==-1 is not sufficient - the
crash happens in the other slot then. Let us skip emitting the signal in
FlowView if index==-1 rather than return early from both slots.
Steps to reproduce 1:
1. Launch YACReaderLibrary version that matches the version of the
default library database. Alternatively, select a compatible library
after starting the application.
2. If InfoComicsView is not active, switch to it.
3. (optional) Switch …

Library: fix InfoComicsView crashes

---

YACReaderLibrary/db/folder_query_result_processor.cpp
YACReaderLibrary/library_window.cpp
YACReaderLibrary/library_window.h

`FolderQueryResultProcessor` has a `ConcurrentQueue` data member. The leak meant that the thread was not joined before exit.

Library: don't leak folderQueryResultProcessor at exit

---

YACReaderLibrary/db/comic_model.cpp

This was a temporary debug output. Not useful anymore.

Library: don't print errors when search edit's text changes

---

config.pri

Qmake by default creates lots of unnecessary information during builds which makes it hard to extract warnings and errors from the log.
This PR adds the undocumented silent parameter to make it less talkactive.

Add CONFIG += silent to build to reduce log pollution

---

YACReaderLibrary/YACReaderLibrary.pro
YACReaderLibrary/comic_vine/comic_vine_all_volume_comics_retriever.cpp
YACReaderLibrary/comic_vine/comic_vine_dialog.cpp
YACReaderLibrary/comic_vine/comic_vine_dialog.h
YACReaderLibrary/comic_vine/model/response_parser.cpp
YACReaderLibrary/comic_vine/model/volume_comics_model.cpp
YACReaderLibrary/comic_vine/model/volumes_model.cpp
YACReaderLibrary/comic_vine/scraper_results_paginator.cpp
YACReaderLibrary/comic_vine/select_comic.cpp
YACReaderLibrary/comic_vine/select_volume.cpp
azure-pipelines-windows-template.yml
azure-pipelines.yml
ci/win/build_installer.iss

QtScript is deprecated and this was needed to start supporting Qt6
This has been cherry-picked and fixed from: https://github.com/u19809/yacreader/tree/No-QtScript-and-Warnings all the code in the branch assumed that JSON object were all maps, but there are a bunch of objects coming from Comic Vine that are Arrays, so the hole thing was pretty much broken.

fix: Replace QtScript with QJson*

---

azure-pipelines.yml

With the transition to Qt6 in brew our CI is now failing on macOS. This PR changes the brew package to the new Qt5 qt@5 package so we can build on mac again.

Azure: Use qt@5 brew package to install Qt5 on macOS

---

YACReader/render.cpp

Switching comics too fast in YACReader can lead to an accumulation of comic threads which are in different stages of parsing, processing and ultimatively cleanup. While these threads and the comic objects are usually disconnected from the render when spawning a new thread, the nature of Qt's queued connection and thread scheduling by the operating system leads to the situation that the disconnection and thread cleanup does not take effect immediately.
As thread disconnection and cleanup is not reliable, race conditions occur.
This PR protects against a race condition where the number of pages the render tries to prepare is set via a signal from the comic object. If this value is set by a stray comic thread while loading a comic, the false value in combination with a bookmarked page index …

Render: Protect against race condition in setNumPages

---

azure-pipelines.yml

Update Ubuntu VM to 18.04 and remove external kubuntu backports PPA
previously used to get Qt packages.
While we're at it, remove libglu1-mesa-dev package too. The external
repo for libunarr is still needed as Ubuntu 18.04 does not package
it yet (it is included in 20.04)

Azure: Update Ubuntu VM to 18.04

---

YACReader/YACReader.pro
YACReaderLibrary/YACReaderLibrary.pro
common/gl/yacreader_flow_gl.cpp

Qt OpenGL in Qt5 is a deprecated module that is discouraged for
new code usage. We have been including this module in our builds
despite not relying on its functionality for a long time now -
probably an oversight from porting to the newer functions.
Time to remove it.
IMPORTANT INFORMATION: In Qt6, a lot of functionality that was
provided by Qt GUI was moved into the 'new' Qt6 Qt OpenGL module.
Thus, even if it makes perfectly sense to remove it for Qt5 builds
we will likely have to restore it for Qt6 builds at a later time.

Remove unneeded QtOpenGL dependency

---

YACReader/main_window_viewer.cpp
YACReaderLibrary/db/comic_model.cpp
YACReaderLibrary/db/folder_model.cpp
YACReaderLibrary/db/reading_list_model.cpp
YACReaderLibrary/db_helper.cpp
YACReaderLibrary/images.qrc
YACReaderLibrary/library_creator.cpp
YACReaderLibrary/library_window.cpp
YACReaderLibrary/server/controllers/v1/foldercontroller.cpp
common/gl/yacreader_flow_gl.cpp
common/gl/yacreader_flow_gl.h
shortcuts_management/actions_shortcuts_model.cpp

Fix some compiler warnings

---

YACReaderLibrary/comic_vine/model/volume_comics_model.cpp
YACReaderLibrary/server/controllers/v2/foldercontentcontroller_v2.cpp
config.pri
custom_widgets/yacreader_treeview.cpp

This PR improves our Qt version check macros for Qt 5 and fixes a false positive in the check that triggered when attempting to build using Qt 6.
Additionally, it increases the minimum build requirement to Qt 5.9 and introduces Qt deprecation macros as they are standard with every new Qt project.
This means that with the merge of this PR all use of Qt functions deprecated with 5.9 or earlier will lead to a build failure and newer Qt versions will display warnings when using functions deprecated after 5.9. This will allow us to defend against such functions sneaking back in and to start migrating away from functions deprecated in later versions. This is also a necessary step for future Qt 6 compatibility.

Build/qt 5.9

---

YACReaderLibrary/server/controllers/v1/folderinfocontroller.cpp
YACReaderLibrary/server/controllers/v1/pagecontroller.cpp
YACReaderLibrary/server/controllers/v2/folderinfocontroller_v2.cpp
YACReaderLibrary/server/controllers/v2/pagecontroller_v2.cpp
YACReaderLibrary/server/controllers/v2/readinglistinfocontroller_v2.cpp
YACReaderLibrary/server/controllers/v2/taginfocontroller_v2.cpp
YACReaderLibrary/server/controllers/v2/updatecomiccontroller_v2.cpp

Hopefully the code does not rely on the side effects of the removed call to `DBHelper::getLibraryName()`.
If the call to `DBHelper::getLibraryName()` is useful, either the variable assignment should be removed or an explaining comment should be added.

PageController*::service: remove unused libraryName variable

---

azure-pipelines-windows-template.yml
azure-pipelines.yml

Qt 5.15.2 and VS 2019 support all Windows platforms still supported
by YACReader. Update the build to take advantage of it.

Azure: Update Windows builds to use VS 2019 and Qt 5.15.2

---

YACReaderLibrary/yacreader_navigation_controller.cpp

When _Back_ or _Forward_ action was triggered, the toolbar title was not updated to match the reselected entry.
I am calling `LibraryWindow::setToolbarTitle()` from `selectedIndexFromHistory()` rather than `loadIndexFromHistory()`, because the latter is also called from `YACReaderNavigationController::loadPreviousStatus()`, which in turn is called only from `LibraryWindow::setSearchFilter()` when the search line text becomes empty. The toolbar title is already correct and does not have to be updated in this case.
My code analysis and experiments have revealed that YACReader code never creates `YACReaderLibrarySourceContainer` objects of type `None`. This type could be removed altogether along with `YACReaderLibrarySourceContainer`'s
default constructor, but for `Q_DECLARE_METATYPE` …

Library: update toolbar title on history navigation

---

YACReaderLibrary/library_window.cpp

Library: don't crash at exit after a folder or a comic is deleted

---

CHANGELOG.md
YACReader.desktop

according to the IANA, [`application/vnd.comicbook+zip`](https://www.iana.org/assignments/media-types/application/vnd.comicbook+zip) and [`application/vnd.comicbook-rar`](https://www.iana.org/assignments/media-types/application/vnd.comicbook-rar) are the correct mimetypes for cbz and cbr. i was having issues getting `xdg-open` to open my cbz and this fixed the issue

Add updated mime-types to YACReader.desktop

---

YACReader.pro
YACReader/YACReader.pro
YACReaderLibrary/YACReaderLibrary.pro
YACReaderLibrary/db/comic_query_result_processor.cpp
YACReaderLibrary/db/folder_query_result_processor.cpp
YACReaderLibraryServer/YACReaderLibraryServer.pro
azure-pipelines-windows-template-qt6.yml
azure-pipelines-windows-template.yml
azure-pipelines.yml
common/concurrent_queue.cpp
common/concurrent_queue.h
config.pri
tests/concurrent_queue_test/concurrent_queue_test.cpp
tests/concurrent_queue_test/concurrent_queue_test.pro
tests/qt_test.pri
tests/tests.pro

I figured that *concurrent_queue_test* does not require any sophisticated testing framework features. Since Qt Test works just fine for this purpose, I decided not to try out *Catch2* (as discussed in #201) for now.
Downsides of setting up a *Catch2 v3* development version dependency right now:
1. The development version is not yet very stable or well-documented. So YACReader's testing code might require frequent revisions when *Catch2* is updated.
2. *Catch2* is built with CMake, which is the build system YACReader is going to adopt in the future (see #73). But until CMake is actually adopted, mixing qmake and CMake can be unwieldy and inconvenient.
3. YACReader code is generally poorly prepared for testing, so I don't expect many tests to be written …

Test, fix, improve, optimize ConcurrentQueue

---

YACReader/Info.plist

Currently YACReader will default to higher-end discrete GPU for OpenGL calls. This increases the battery usage while having no need for a high performance device. This flag tells MacOS that switching to integrated GPU is acceptable in this app. As a result, YACReader will use integrated GPU in Macs that support automatic graphics switching.
References:
https://developer.apple.com/library/archive/qa/qa1734/_index.html
https://developer.apple.com/documentation/bundleresources/information_property_list/nssupportsautomaticgraphicsswitching?language=objc

Enable using integrated GPU in Dual GPU Macs

---

YACReader/YACReader.pro
YACReader/main.cpp
YACReader/yacreader_de.ts
YACReader/yacreader_en.ts
YACReader/yacreader_es.ts
YACReader/yacreader_fr.ts
YACReader/yacreader_it.ts
YACReader/yacreader_nl.ts
YACReader/yacreader_pt.ts
YACReader/yacreader_ru.ts
YACReader/yacreader_tr.ts
YACReader/yacreader_zh_CN.ts
YACReader/yacreader_zh_HK.ts
YACReader/yacreader_zh_TW.ts
YACReaderLibrary/YACReaderLibrary.pro
YACReaderLibrary/main.cpp
YACReaderLibrary/yacreaderlibrary_de.ts
YACReaderLibrary/yacreaderlibrary_en.ts
YACReaderLibrary/yacreaderlibrary_es.ts
YACReaderLibrary/yacreaderlibrary_fr.ts
YACReaderLibrary/yacreaderlibrary_it.ts
YACReaderLibrary/yacreaderlibrary_nl.ts
YACReaderLibrary/yacreaderlibrary_pt.ts
YACReaderLibrary/yacreaderlibrary_ru.ts
YACReaderLibrary/yacreaderlibrary_tr.ts
YACReaderLibrary/yacreaderlibrary_zh_CN.ts
YACReaderLibrary/yacreaderlibrary_zh_HK.ts
YACReaderLibrary/yacreaderlibrary_zh_TW.ts
config.pri

Older versions of the Qt documentation advocate using QLocale::system::name for system language resolving. This is deprecated and causes misbehavior, such as selecting the system unit language instead of system display language on Windows.
Solution: Use QTranslator::load(QLocale(), ... ...), which is display language aware.
@luisangelsm the following things need to be tested:
[ ] Correct directory resolution on Win and MacOS
[ ] Working languages on Win and MacOS

Translations: Don't use QLocale::system::name

---

YACReaderLibrary/server/yacreader_http_server.cpp

When starting the server, the paths for docroot and templates are always overwritten. This is a serious problem when developing or debugging outside of an installation.
Solution: Only write the settings if they are not present!

Server: Don't overwrite template and docroot path

---

YACReader/YACReader.pro
YACReaderLibrary/YACReaderLibrary.pro
YACReaderLibraryServer/YACReaderLibraryServer.pro
config.pri

The introduction of CONFIG+= lrelease introduced a regression in the installation of translation files on systems using make install targets.
This is fixed by replacing the old translation targets with the target supplied by lrelease.
Fixes #349

Unix: Fix regression in translation install target

---

CHANGELOG.md
third_party/QsLog/QsLog.pri

When shutting down our apps, we clean up some ressources after app.exec() has finished. As our logger runs on the apps main thread, it can no longer respond to any debug messages generated during the cleanup phase.
This can lead to segfaults and error masking.
Solution: Run QsLog in a dedicated thread.

QsLog: Use dedicated logging thread to avoid segfaults during app shutdown

---

CHANGELOG.md
YACReaderLibrary/initial_comic_info_extractor.cpp
common/comic.cpp
common/comic.h
common/pdf_comic.h
dependencies/pdf_backend.pri

This PR adds support for the Poppler Qt6 backend
@jbeich feel free to give it a test, feedback is always welcome.

Add support for poppler-qt6 pdf backend

---

CHANGELOG.md
YACReader/YACReader.pro
YACReaderLibrary/YACReaderLibrary.pro
YACReaderLibrary/ip_config_helper.cpp
YACReaderLibrary/ip_config_helper.h
YACReaderLibrary/server_config_dialog.cpp
YACReaderLibraryServer/YACReaderLibraryServer.pro
YACReaderLibraryServer/main.cpp

This PR introduces the following changes:
1. Refactoring of our IP interface detection and sorting code
- Replace system specific functions with Qt functions
- Move code in dedicated helper function for better reuse
- Remove system specific workarounds for haiku OS (no longer needed)
2. Print QR code on headless server start
- Print a QR code and IP information using the refactoring in 1
The following tests should be performed: 
1. Check if detection and sorting of interfaces works as expected
- All wanted devices
- No unwanted devices like localhost and/or loopback
- Correct order
2. Check if the QR code prints correctly on Windows and macOS terminals (uses unicode, might need adjustmens for Windows)

New qr engine, part II

---

YACReaderLibraryServer/main.cpp
third_party/QsLog/QsLogDestConsole.cpp

Fix for two problems:
1. QsLog output was not shown on the Windows Console
2. QRCode unicode characters for YACReaderLibraryServer's new console QR code were not correctly encoded on Windows machines
@luisangelsm We should probably add 1 to our changelog for the upcoming release

New qr engine: Fix output on Windows

---

YACReaderLibrary/db/comic_model.cpp
common/comic_db.cpp
config.pri

When creating switch case structures, please don't forget the default case or you can have invalid control flows in your code :)

ComicInfo::getTypeString: Return an empty string for unhandled enums

---

common/comic_db.h

When doing modularized builds, the definition of YACReaderComicInfoPair as a metatype can lead to redefinition of Qt internal metatypes at the moc stage. This is currently not happening in qmake, but is a problem for our CMake migartion.
As we don't really use this type, it is safe to remove.

Remove YACReaderComicInfoPair metatype

---

YACReader/main_window_viewer.cpp
YACReaderLibrary/db/comic_model.cpp

This adds the 7z format in file selection dialog and database for builds with a recent enough Unarr version.

Unarr: Enable 7z for unarr 1.1.x +

---

CHANGELOG.md
YACReaderLibrary/images.qrc
YACReaderLibrary/library_window.cpp
YACReaderLibrary/properties_dialog.cpp
YACReaderLibrary/properties_dialog.h
common/comic_db.cpp
common/comic_db.h
common/yacreader_global_gui.cpp
common/yacreader_global_gui.h
custom_widgets/custom_widgets_yacreaderlibrary.pri
custom_widgets/yacreader_cover_label.cpp
custom_widgets/yacreader_cover_label.h
images/loadCustomCover.svg
images/resetCover.svg

* you can drag&drop an image into the cover view of the edit dialog to set it or use the button in the cover box tools
* there is a reset button too to restore the default cover
* and you can edit covers in bulk, so if you select various comics -> edit -> you can set the same cover for all of them, specially helpful when you have a list of web comics without covers

Custom comic covers
