YACReader/yacreader

YACReader/main_window_viewer.cpp
YACReaderLibrary/comic_vine/sort_volume_comics.cpp
YACReaderLibrary/db/folder_model.cpp
YACReaderLibrary/server/lib/httpserver/httprequest.cpp
YACReaderLibrary/server/lib/logging/filelogger.cpp
custom_widgets/yacreader_options_dialog.cpp

This PR fixes a bunch of problems found by the clang static code analyzer.

9.5.0 bugfixes

---

YACReaderLibrary/yacreaderlibrary_ru.ts

Text correction, minor corrections.

Edit Russian translation.

---

.travis.yml
appveyor.yml

Add Travis for OS X and Linux (Ubuntu), Appveyor for Windows builds.
You still need to activate those services for the git repo, set a default branch (develop I guess) and add badges.

Set up continuous integration

---

YACReader/goto_flow.cpp
YACReaderLibrary/comic_flow_widget.cpp
YACReaderLibrary/library_window.cpp
common/pictureflow.cpp

See details in the commit messages.

Miscellaneous code fixes

---

YACReaderLibrary/db_helper.cpp
YACReaderLibrary/db_helper.h
YACReaderLibrary/server/controllers/v2/synccontroller_v2.cpp

Timeouts were a problem before.

Use db transactions when updating the progress from iOS

---

common/gl/yacreader_flow_gl.cpp
common/gl/yacreader_flow_gl.h

This PR adds raytracing and reenables antialiasing for the OpenGL coverflow.

Raytracing and Antialiasing

---

YACReader/viewer.cpp

Without this commit the horizontal wheel on a two-wheel mouse acts the
same as the vertical wheel in YACReader.
horizontalScroller is used analogously to verticalScroller in
Viewer::scrollTo(). So I made the horizontal wheel work analogously to
the vertical wheel except for moving to the next or previous page.

Reader: add support for horizontal mouse wheel

---

YACReader/goto_flow.cpp
YACReader/goto_flow.h

goto_flow fixes

---

common/yacreader_global.h
config.pri
dependencies/pdf_backend.pri

Fixed PDF support in macos by switching to pdfkit

9.6.1 Release

---

YACReader/main_window_viewer.cpp
YACReaderLibrary/library_window.cpp
common/yacreader_global.h

It fixes fullscreen mode in Windows.

9.6.2 release

---

azure-pipelines-windows-template.yml
azure-pipelines.yml

Other changes:
- Use macos catalina
- Fix Windows builds by including QtScript in Qt installation

Update azure pipelines to work on forked repos

---

YACReader/yacreader_nl.ts
YACReaderLibrary/yacreaderlibrary_nl.ts

Updated Dutch translation

---

YACReaderLibrary/server/startup.cpp

When setting ports, temporary or for good, we need to go via the config
files and not QTcpServer or we get undefined behavior. To support temp
ports, we need to back up the fixed port in the settings and restore at the
next start.
This PR fixes #177 and restores port 8080 as default.

Fix port settings

---

YACReader/YACReader.pro
YACReaderLibrary/YACReaderLibrary.pro
YACReaderLibraryServer/YACReaderLibraryServer.pro
config.pri

Disable standard assert() macro in Release builds, deduplicate `CONFIG += c++11`

---

YACReaderLibrary/db/comic_model.h
YACReaderLibrary/db/folder_model.h
YACReaderLibrary/db/reading_list_model.h
YACReaderLibrary/library_window.cpp

Library: don't leak DB model objects

---

YACReaderLibrary/YACReaderLibrary.pro
YACReaderLibrary/db/comic_query_result_processor.cpp
YACReaderLibrary/db/comic_query_result_processor.h
YACReaderLibrary/library_window.cpp
YACReaderLibrary/library_window.h

See also the second commit message.

Fix a typo in ComicQueryResultProcessor class name

---

CHANGELOG.md
INSTALL.md
compressed_archive/README_7zip.txt
compressed_archive/unarr/README.txt

This PR translates the spanish parts of the changelog to english and slightly updates the build instructions.
Fixes #152

Translate changelog and update build instructions

---

YACReader/main.cpp
YACReader/main_window_viewer.cpp
YACReader/main_window_viewer.h
YACReader/yacreader_local_client.cpp
YACReader/yacreader_local_client.h
YACReaderLibrary/YACReaderLibrary.pro
YACReaderLibrary/db/comic_model.cpp
YACReaderLibrary/db/comic_model.h
YACReaderLibrary/db_helper.cpp
YACReaderLibrary/db_helper.h
YACReaderLibrary/library_comic_opener.cpp
YACReaderLibrary/library_comic_opener.h
YACReaderLibrary/library_window.cpp
YACReaderLibrary/library_window.h
YACReaderLibrary/server/controllers/v2/comiccontroller_v2.cpp
YACReaderLibrary/server/controllers/v2/comiccontroller_v2.h
YACReaderLibrary/server/controllers/v2/comiccontrollerinreadinglist_v2.cpp
YACReaderLibrary/server/controllers/v2/comiccontrollerinreadinglist_v2.h
YACReaderLibrary/server/controllers/v2/pagecontroller_v2.cpp
YACReaderLibrary/server/requestmapper.cpp
YACReaderLibrary/server/server.pri
YACReaderLibrary/yacreader_local_server.cpp
YACReaderLibrary/yacreader_local_server.h
common/yacreader_global.cpp
common/yacreader_global.h
custom_widgets/whats_new_dialog.cpp

It is more a fix than a feature but it wasn't really a bug.

Feature: Improve reading lists

---

YACReader/Info.plist
YACReaderLibrary/Info.plist
compileOSX.sh

Followup to https://github.com/YACReader/yacreader/issues/31#issuecomment-866274780. Untested in your setup, but it should work if I’m understanding it correctly.
Fixes https://github.com/YACReader/yacreader/issues/31.

compileOSX.sh: add version to app

---

YACReaderLibrary/library_window.cpp
YACReaderLibrary/library_window.h
YACReaderLibrary/yacreader_navigation_controller.cpp

Library: exit search mode before creating a folder

---

README.md

I have fixed some spelling mistakes and grammatical errors of the README.md file. I hope you will accept my PR.  If anything wrong in my PR, please provide a feedback.  Thanks in Advance

Fixed some spelling & grammatical issue of README

---

CHANGELOG.md
third_party/QtWebApp/httpserver/httpconnectionhandler.h
third_party/QtWebApp/httpserver/httpconnectionhandlerpool.cpp
third_party/QtWebApp/httpserver/httpconnectionhandlerpool.h
third_party/QtWebApp/httpserver/httpglobal.cpp
third_party/QtWebApp/httpserver/httpglobal.h
third_party/QtWebApp/httpserver/httplistener.h
third_party/QtWebApp/httpserver/httprequest.h
third_party/QtWebApp/httpserver/staticfilecontroller.cpp
third_party/QtWebApp/lgpl-3.0.txt
third_party/QtWebApp/readme.txt
third_party/QtWebApp/releasenotes.txt
third_party/QtWebApp/templateengine/templateglobal.h
third_party/README.md

This PR updates our internal QtWebApp copy to v1.8.6

Update QtWebApp, v1.8.3 to v1.8.6

---

YACReaderLibrary/YACReaderLibrary.pro
YACReaderLibrary/db/comic_model.cpp
YACReaderLibrary/db/comic_model.h
YACReaderLibrary/db/folder_model.cpp
YACReaderLibrary/db/folder_model.h
YACReaderLibrary/folder_content_view.cpp
YACReaderLibrary/folder_content_view.h
YACReaderLibrary/grid_comics_view.cpp
YACReaderLibrary/grid_comics_view.h
YACReaderLibrary/library_window.cpp
YACReaderLibrary/library_window.h
YACReaderLibrary/qml.qrc
YACReaderLibrary/qml/FolderContentView.qml
YACReaderLibrary/qml/FolderContentView6.qml
YACReaderLibrary/qml6.qrc
YACReaderLibrary/yacreader_comics_views_manager.cpp
YACReaderLibrary/yacreader_comics_views_manager.h
YACReaderLibrary/yacreader_navigation_controller.cpp
common/folder.cpp
common/folder.h

A new view to replace the old and boring `EmptyFolderWidget`.
It needs some more work, specially the `continue reading` banner (which doesn't auto-update yet), but it is already better than `EmptyFolderWidget`

feature: Folder content view

---

YACReader/yacreader_de.ts

I'm a native German speaker, so I fixed errors in the German translations that were already present in the file and added all missing translations. I'd be delighted if you could count this PR as my contribution to HAcktoberfest. 💖

Added missing German translations and fixed errors

---

YACReaderLibrary/yacreaderlibrary_de.ts

As requested, I have added all unfinished German translations.

Added unfinished German translations

---

CHANGELOG.md
YACReaderLibrary/db_helper.cpp
YACReaderLibrary/db_helper.h
YACReaderLibrary/server/controllers/v2/comicfullinfocontroller_v2.cpp
YACReaderLibrary/server/controllers/v2/favoritescontroller_v2.cpp
YACReaderLibrary/server/controllers/v2/foldercontentcontroller_v2.cpp
YACReaderLibrary/server/controllers/v2/foldermetadatacontroller_v2.cpp
YACReaderLibrary/server/controllers/v2/foldermetadatacontroller_v2.h
YACReaderLibrary/server/controllers/v2/librariescontroller_v2.cpp
YACReaderLibrary/server/controllers/v2/readingcomicscontroller_v2.cpp
YACReaderLibrary/server/controllers/v2/readinglistcontentcontroller_v2.cpp
YACReaderLibrary/server/controllers/v2/readinglistscontroller_v2.cpp
YACReaderLibrary/server/controllers/v2/synccontroller_v2.cpp
YACReaderLibrary/server/controllers/v2/tagcontentcontroller_v2.cpp
YACReaderLibrary/server/controllers/v2/tagscontroller_v2.cpp
YACReaderLibrary/server/requestmapper.cpp
YACReaderLibrary/server/server.pri
YACReaderLibrary/server/yacreader_server_data_helper.cpp
YACReaderLibrary/server/yacreader_server_data_helper.h
YACReaderLibrary/yacreader_libraries.cpp
YACReaderLibrary/yacreader_libraries.h
common/yacreader_global.h

Updates required by the new Android client

Server 2.1 (9.14.1)
